
name: december

default-extensions:
- DisambiguateRecordFields
- DuplicateRecordFields
- NoFieldSelectors
- OverloadedRecordDot
- DerivingStrategies
- BlockArguments
- LambdaCase
- ImportQualifiedPost
- NamedFieldPuns
- DeriveFunctor
- ScopedTypeVariables
- UndecidableInstances
- FlexibleInstances
- GeneralizedNewtypeDeriving
- DeriveAnyClass
- DeriveTraversable
- DeriveFoldable
- DeriveGeneric
- PatternSynonyms
- DataKinds
- RankNTypes
- FlexibleContexts
- TypeApplications
- ConstraintKinds
- OverloadedStrings

dependencies:
- base
- containers
- polysemy
- yard
- unification-xd
- text
# - mptc

library:
  source-dirs: src

ghc-options: -freverse-errors

executables:
  dec:
    source-dirs: app
    dependencies:
    - december

    main: Main.hs