
name: december

default-extensions:
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DisambiguateRecordFields
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- NoFieldSelectors
- OverloadedRecordDot
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- UndecidableInstances

dependencies:
- base
- containers
- polysemy
- yard
- unification-xd
- text
# - mptc

library:
  source-dirs: src

ghc-options: -freverse-errors

executables:
  dec:
    source-dirs: app
    dependencies:
    - december

    main: Main.hs